-------------------
---Bookie  v1.10---
---GLOBAL CONFIG---
-------------------
Config = {}

Config.max_pot = 35
Config.min_bet = 10
Config.max_bet = 150
Config.step = 10
Config.time_till_next_match = 60000 -- Ms {1 min}
Config.prompt_group_name = "Bookie" --Main Prompt Group Name
Config.start_control = 0xC7B5340A -- [ENTER]
Config.start_control_name = "Place Bet" --Place Bet
Config.bet_control = 0x6319DB71 -- [UP]
Config.bet_control_down = 0x05CA7C52 -- [DOWN]
Config.bet_control_name = "Bet $ "
Config.select_control = 0xDEB34313 -- [RIGHT]
Config.select_control_two = 0xA65EBAB4 -- [LEFT]
Config.debugger = false
Config.show_names = true
Config.show_bookie_pot = true
Config.fake_bets = true
--- Max of 2 Players ( fighters )
Config.players = {
    [1] = {
        ped = nil,
        pos = {X= -245.25675964355, Y= 663.33233642578, Z= 112.34589385986, H= 277.64520263672},
        model = "U_M_M_AsbPrisoner_01",
        voice = "0130_G_M_M_UNICRIMINALS_01_WHITE_01",
        fake_name = "Bob Lazar",
        isNetwork = true,
        max_health = 200,
    },
    [2] = {
        ped = nil,
        pos= {X= -227.55389404297, Y= 667.76770019531, Z= 112.30582427979, H= 103.1782913208},
        model= "U_M_M_AsbPrisoner_02",
        voice= "0131_G_M_M_UNICRIMINALS_01_WHITE_02",
        fake_name = "Eric Smith",
        isNetwork = true,
        max_health = 200,
    },
}
--- Max 1 Bookie
Config.bookies = {
    [1] = {
        ped = nil,
        --pos = {X= -237.13830566406, Y= 655.77703857422, Z= 112.32099914551, H= 322.51000976563},
        pos = {X= -240.97523498535, Y= 658.92657470703, Z= 112.32802581787, H= 156.49337768555},
        model = "U_M_M_ARMUNDERTAKER_01",
        --model = "CS_hobartcrawley",
        voice = "1080_U_M_M_ARMUNDERTAKER_01",
        fake_name = "Bookie",
        isNetwork = false,
    },
}

-- NO FEMALES | NO TEENS | NO LAW | NO DEAD | NO RICH PEOPLE | NO STORE OWNERS
-- Most of these names are generated, and do not resemble Rockstar names
Config.named_ped_list = {
    {name="Henry Donnell",model="CS_forgivenhusband_01"},
    {name="Francis Sinclair",model="CS_FRANCIS_SINCLAIR"},
    {name="Charles Châtenay",model="CS_FRENCHMAN_01"},
    {name="Alberto Fussar",model="CS_fussar"},
    {name="Gareth Braithwaite",model="CS_garethbraithwaite"},
    {name="Gavin Atkinson",model="CS_GAVIN"},
    {name="genstorymale",model="CS_genstorymale"},
    {name="Gerald Braithwaite",model="CS_geraldbraithwaite"},
    {name="Erwin Müller",model="CS_GermanFather"},
    {name="Gilbert Knightly",model="CS_GILBERTKNIGHTLY"},
    {name="Grizzled Jon",model="CS_GrizzledJon"},
    {name="Hamish Sinclair",model="CS_HAMISH"},
    {name="Hector Fellowes",model="CS_hectorfellowes"},
    {name="Henri Lemiux",model="CS_henrilemiux"},
    {name="John Bartram",model="CS_HERBALIST"},
    {name="Hercule",model="CS_hercule"}, -- not working ?  ? ? vs strawberryoutlaw_01
    {name="Heston Jameson",model="CS_HestonJameson"},
    {name="Hobart Crawley",model="CS_hobartcrawley"},
    {name="Ian Gray",model="CS_IANGRAY"},
    {name="Jamie Gillis",model="CS_JAMIE"},
    {name="Martin Janson",model="CS_JANSON"},
    {name="Javier Escuella",model="CS_javierescuella"},
    {name="Jeb",model="CS_Jeb"},
    {name="Jim Calloway",model="CS_jimcalloway"},
    {name="Jock Gray",model="CS_jockgray"},
    {name="Joe Bedford",model="CS_JOE"},
    {name="JOHN THE BAPTI SINGMADMAN",model="CS_JOHNTHEBAPTISINGMADMAN"},
    {name="John Weathers",model="CS_JohnWeathers"},
    {name="Josiah Trelawny",model="CS_josiahtrelawny"},
    {name="Jules Prioleau",model="CS_Jules"},
    {name="John Karen",model="CS_KarensJohn_01"},
    {name="Kieran Duffy",model="CS_kieran"},
    {name="Leigh Gray",model="CS_leighgray"},
    {name="Leon Fuentes",model="CS_leon"},
    {name="Levi Simon",model="CS_LeviSimon"},
    {name="Leviticus cornwall",model="CS_leviticuscornwall"},
    {name="Jacob Londonderry",model="CS_LondonderrySon"},
    {name="Monk",model="CS_MEDITATINGMONK"},
    {name="Milton andrews",model="CS_miltonandrews"},
    {name="Alfredo Montez",model="CS_MP_ALFREDO_MONTEZ"},
    {name="Ross Newman",model="CS_mud2bigguy"},
    {name="Kevin Wilder",model="CS_MysteriousStranger"},
    {name="Nbx Drunk",model="CS_NbxDrunk"},
    {name="Nial Whelan",model="CS_NIAL_WHELAN"},
    {name="Nicholas Timmins",model="CS_NicholasTimmins"},
    {name="Nils Skot",model="CS_NILS"},
    {name="Norris Forsythe",model="CS_NorrisForsythe"},
    {name="Obediah Hinton",model="CS_obediahhinton"},
    {name="Bertram Guyet",model="CS_oddfellowspinhead"},
    {name="Paytah Anthony",model="CS_PAYTAH"},
    {name="Pinkerton Goon",model="CS_PinkertonGoon"},
    {name="Troy Fields",model="CS_PoisonWellShaman"},
    {name="Joe Burns",model="CS_POORJOE"},
    {name="Professor Bell",model="CS_professorbell"},
    {name="Rains Fall",model="CS_rainsfall"},
    {name="Ramon Cortez",model="CS_RAMON_CORTEZ"},
    {name="Rhodes Assistant",model="CS_RhodesAssistant"},
    {name="Harper Richardson",model="CS_rhodeskidnapvictim"},
    {name="Clark Woods",model="CS_rhodessaloonbouncer"},
    {name="Saul Kamden",model="CS_ringmaster"},
    {name="Michael Harrison",model="CS_samaritan"},
    {name="Scott Gray",model="CS_SCOTTGRAY"},
    {name="Jonathan Kennedy",model="CS_SDSALOONDRUNK_01"},
    {name="Sean Wallace",model="CS_sean"},
    {name="Bob Brownlee",model="CS_SUNWORSHIPPER"},
    {name="Swamp Freak",model="CS_SwampFreak"},
    {name="Jaeden Osborne",model="CS_SWAMPWEIRDOSONNY"},
    {name="Tavish Gray",model="CS_tavishgray"},
    {name="Theodore Levin",model="CS_theodorelevin"},
    {name="Thomas Down",model="CS_thomasdown"},
    {name="Timothy Donahue",model="CS_TimothyDonahue"},
    {name="Ken Jennings",model="CS_TINYHERMIT"},
    {name="Tom Dickens",model="CS_tomdickens"},
    {name="Town Crier",model="CS_TownCrier"},
    {name="TREASURE HUNTER",model="CS_TREASUREHUNTER"},
    {name="Acrisius Patterson",model="CS_twinbrother_01"},
    {name="Proetus Patterson",model="CS_twinbrother_02"},
    {name="John O'Creagh",model="CS_uncle"},
    {name="Reuben Kent",model="CS_UNIDUSTERJAIL_01"},
    {name="Nathan Whitley",model="CS_valauctionboss_01"},
    {name="Charlie Rivers",model="CS_ValPrayingMan"},
    {name="Deegan Ball",model="CS_WapitiBoy"},
    {name="Eric Warvet",model="CS_warvet"},
    {name="Dominick Watson",model="CS_WATSON_01"},
    {name="Todd Bush",model="CS_WATSON_02"},
    {name="Matthew Reynolds",model="CS_WATSON_03"},
    {name="Chad McKay",model="CS_WELSHFIGHTER"},
    {name="Winton Holmes",model="CS_WintonHolmes"},
    {name="Wrobel Kowalczyk",model="CS_Wrobel"},
    {name="Zak Davis",model="G_M_M_BountyHunters_01"},
    {name="Ernesto Stanton",model="G_M_M_UniAfricanAmericanGang_01"},
    {name="Arthur Wilson",model="G_M_M_UniBanditos_01"},
    {name="Dax Pope",model="G_M_M_UniBraithwaites_01"},
    {name="Colin Armstrong",model="G_M_M_UniBronteGoons_01"},
    {name="Hector Townsend",model="G_M_M_UniCornwallGoons_01"},
    {name="Alfie Baker",model="G_M_M_UniCriminals_01"},
    {name="James Lucas",model="G_M_M_UniCriminals_02"},
    {name="Chris Wells",model="G_M_M_UniDuster_01"},
    {name="Kristopher Lyon",model="G_M_M_UniDuster_02"},
    {name="Josiah Frost",model="G_M_M_UniDuster_03"},
    {name="Marcel Bean",model="G_M_M_UniDuster_04"},
    {name="Harley Davids",model="G_M_M_UNIDUSTER_05"},
    {name="David White",model="G_M_M_UniGrays_01"},
    {name="Kody Jackson",model="G_M_M_UniGrays_02"},
    {name="Brady Dillon",model="G_M_M_UniInbred_01"},
    {name="Emery Langston",model="G_M_M_UNILANGSTONBOYS_01"},
    {name="Dawson Marsh",model="G_M_M_UNIMICAHGOONS_01"},
    {name="Dane Ballard",model="G_M_M_UniMountainMen_01"},
    {name="Brandon Morgan",model="G_M_M_UniRanchers_01"},
    {name="Samuel Dixon",model="G_M_M_UNISWAMP_01"},
    {name="Archie Willis",model="G_M_O_UniExConfeds_01"},
    {name="Larry Weaver",model="G_M_Y_UniExConfeds_01"},
    {name="Declan Fraser",model="G_M_Y_UNIEXCONFEDS_02"},
    {name="Stanley Dean",model="MBH_SKINNERSEARCH_MALES_01"},
    {name="Taylor Kinney",model="MES_ABIGAIL2_MALES_01"},
    {name="Freddie Rees",model="MES_FINALE2_MALES_01"},
    {name="David Hunter",model="MES_FINALE3_MALES_01"},
    {name="Aidan Jackson",model="MES_MARSTON1_MALES_01"},
    {name="Jamar Pearson",model="MES_MARSTON2_MALES_01"},
    {name="Stefan Shields",model="MES_MARSTON5_2_MALES_01"},
    {name="Maxton Mullins",model="MES_MARSTON6_MALES_01"},
    {name="Sawyer Davenport",model="MES_SADIE4_MALES_01"},
    {name="Dominic Watts",model="MES_SADIE5_MALES_01"},
    {name="Crew Leon",model="MSP_FEUD1_MALES_01"},
    {name="Zak Wilkinson",model="MSP_FUSSAR2_MALES_01"},
    {name="Solomon Black",model="MSP_GANG2_MALES_01"},
    {name="Andrew Burke",model="MSP_GANG3_MALES_01"},
    {name="Fred Hurst",model="MSP_GRAYS1_MALES_01"},
    {name="Patrick Enzo",model="MSP_GRAYS2_MALES_01"},
    {name="Johnny Dotson",model="MSP_GUARMA2_MALES_01"},
    {name="Harvey Burns",model="MSP_INDUSTRY1_MALES_01"},
    {name="Noel Riggs",model="MSP_MARY1_MALES_01"},
    {name="Davis Faulkner",model="MSP_MARY3_MALES_01"},
    {name="Wilson Hunt",model="MSP_MOB0_MALES_01"},
    {name="Jonathan Boyd",model="MSP_MOB1_MALES_01"},
    {name="Ben Rees",model="msp_mob3_MALES_01"},
    {name="Darien Dudley",model="MSP_MUDTOWN3_MALES_01"},
    {name="Josh Chapman",model="MSP_Mudtown3B_Males_01"},
    {name="Keegan Duran",model="MSP_MUDTOWN5_MALES_01"}, --fancy guy ?
    {name="Barrett Aguirre",model="MSP_NATIVE1_MALES_01"},
    {name="Micah Roth",model="MSP_REVEREND1_MALES_01"},
    {name="Arthur Rivers",model="MSP_SAINTDENIS1_MALES_01"},
    {name="Trevon French",model="MSP_SALOON1_MALES_01"},
    {name="Thomas Marsh",model="MSP_SMUGGLER2_MALES_01"},
    {name="Leo Gill",model="MSP_TRAINROBBERY2_MALES_01"},
    {name="Layne Hudson",model="MSP_TRELAWNY1_MALES_01"},
    {name="Spencer Chapman",model="MSP_UTOPIA1_MALES_01"},
    {name="Orlando Workman",model="MSP_WINTER4_MALES_01"},
    {name="Jayson Landry",model="RCES_ABIGAIL3_MALES_01"},
    {name="Joshua Marshall",model="RCES_BEECHERS1_MALES_01"},
    {name="Agustin Lindsay",model="RCES_EVELYNMILLER_MALES_01"},
    {name="Kieran Shaw",model="RCSP_BEAUANDPENELOPE_MALES_01"},
    {name="Luca Fletcher",model="RCSP_CALDERON_MALES_01"},
    {name="Oliver Fletcher",model="RCSP_CALDERONSTAGE2_MALES_01"},
    {name="Flynn Finley",model="RCSP_CALLOWAY_MALES_01"},
    {name="Isaias Hewitt",model="RCSP_COACHROBBERY_MALES_01"},
    {name="Norton Camden",model="RCSP_CRACKPOT_MALES_01"},
    {name="Jax Douglas",model="RCSP_CREOLE_MALES_01"},
    {name="Brandon Blair",model="RCSP_DUTCH1_MALES_01"},
    {name="Michael Reynolds",model="RCSP_DUTCH3_MALES_01"},
    {name="Brandon Hill",model="RCSP_EDITHDOWNES2_MALES_01"},
    {name="Leon Duncan",model="RCSP_FORMYART_MALES_01"},
    {name="Darrell Christian",model="RCSP_GUNSLINGERDUEL4_MALES_01"},
    {name="Derrick Adams",model="RCSP_HEREKITTYKITTY_MALES_0"},
    {name="Billy Willis",model="RCSP_HUNTING1_MALES_01"},
    {name="Randy Long",model="RCSP_MRMAYOR_MALES_01"},
    {name="Gilbert Heath",model="RCSP_NATIVE1S2_MALES_01"},
    {name="Collin Woodard",model="RCSP_ODDFELLOWS_MALES_01"},
    {name="Abram Fox",model="RCSP_POISONEDWELL_MALES_01"},
    {name="Bradley Gamble",model="RCSP_RIDETHELIGHTNING_MALES_01"},
    {name="John Hamilton",model="RCSP_SADIE1_MALES_01"},
    {name="Tommy Byrd",model="RCSP_SLAVECATCHER_MALES_01"},
    {name="Jake Murray",model="RE_ANIMALATTACK_MALES_01"},
    {name="Cristian Hewitt",model="RE_ANIMALMAULING_MALES_01"},
    {name="Kieran Gallagher",model="RE_APPROACH_MALES_01"},
    {name="James Palmer",model="RE_BEARTRAP_MALES_01"},
    {name="Charlie Moses",model="RE_CHECKPOINT_MALES_01"},
    {name="Noah Booth",model="RE_COACHROBBERY_MALES_01"},
    {name="Zayne Bruce",model="RE_CONSEQUENCE_MALES_01"},
    {name="Jacob Webb",model="RE_CORPSECART_MALES_01"},
    {name="Daniel Kaur",model="RE_CRASHEDWAGON_MALES_01"},
    {name="Jerry Butler",model="RE_DARKALLEYAMBUSH_MALES_01"},
    {name="Alvin Sanders",model="RE_DARKALLEYBUM_MALES_01"},
    {name="Clifton Parker",model="RE_DARKALLEYSTABBING_MALES_01"},
    {name="Robert Lee ",model="RE_DOMESTICDISPUTE_MALES_01"},
    {name="Collin Jackson",model="RE_DROWNMURDER_MALES_01"},
    {name="Peter Wilson",model="RE_DRUNKCAMP_MALES_01"},
    {name="Glenn Stewart",model="RE_DRUNKDUELER_MALES_01"},
    {name="Clayton Baker",model="RE_DUELBOASTER_MALES_01"},
    {name="Ed Lewis",model="RE_DUELWINNER_MALES_01"},
    {name="Lawrence West",model="RE_EXECUTIONS_MALES_01"},
    {name="Bennie Forester",model="RE_FLEEINGFAMILY_MALES_01"},
    {name="Eugene Nolan",model="RE_FOOTROBBERY_MALES_01"},
    {name="Martin Ward",model="RE_FUSSARCHASE_MALES_01"},
    {name="Roy Bryant",model="RE_GOLDPANNER_MALES_01"},
    {name="Stanley Murphy",model="RE_HORSERACE_MALES_01"},
    {name="David King",model="RE_HOSTAGERESCUE_MALES_01"},
    {name="Mike Bull",model="RE_INBREDKIDNAP_MALES_01"},
    {name="Wilbur Carter",model="RE_LONEPRISONER_MALES_01"},
    {name="Abraham James",model="RE_LOSTDRUNK_MALES_01"},
    {name="Roger Richardson",model="RE_LOSTFRIEND_MALES_01"},
    {name="Clifford Green",model="RE_LOSTMAN_MALES_01"},
    {name="Virgil Doolin",model="RE_MOONSHINECAMP_MALES_01"},
    {name="Steve Price",model="RE_MURDERCAMP_MALES_01"},
    {name="Allen Ward",model="RE_MURDERSUICIDE_MALES_01"},
    {name="Thomas Jenkins",model="RE_NAKEDSWIMMER_MALES_01"},
    {name="Elijah Green",model="RE_ONTHERUN_MALES_01"},
    {name="Patrick Jones",model="RE_OUTLAWLOOTER_MALES_01"},
    {name="Tom Ross",model="RE_PARLORAMBUSH_MALES_01"},
    {name="Harold Miller",model="RE_PEEPINGTOM_MALES_01"},
    {name="Curtis Miller",model="RE_PICKPOCKET_MALES_01"},
    {name="Otis Reed",model="RE_PISSPOT_MALES_01"},
    {name="Clarence Bailey",model="RE_PLAYERCAMPSTRANGERS_MALES_01"},
    {name="Tim Sanders",model="RE_POISONED_MALES_01"},
    {name="Dave Hill",model="RE_POLICECHASE_MALES_01"},
    {name="Raymond Place",model="RE_PRISONWAGON_MALES_01"},
    {name="Sidney Brown",model="RE_PUBLICHANGING_MALES_01"},
    {name="Gerald Cook",model="RE_RATINFESTATION_MALES_01"},
    {name="Norman Camp",model="RE_ROWDYDRUNKS_MALES_01"},
    {name="Alex Black",model="RE_SAVAGEAFTERMATH_MALES_01"},
    {name="Warren Taylor",model="RE_SAVAGEFIGHT_MALES_01"},
    {name="Everett Johnson",model="RE_SAVAGEWAGON_MALES_01"},
    {name="Joseph Bell",model="RE_SHARPSHOOTER_MALES_01"},
    {name="Howard Smith",model="RE_SHOWOFF_MALES_01"},
    {name="Lester Hall",model="RE_SKIPPINGSTONES_MALES_01"},
    {name="Orville Hill",model="RE_SNAKEBITE_MALES_01"},
    {name="Cecil Harris",model="RE_STALKINGHUNTER_MALES_01"},
    {name="Mason Brown",model="RE_STRANDEDRIDER_MALES_01"},
    {name="Arnold Reed",model="RE_STREET_FIGHT_MALES_01"},
    {name="Marshall Kelly",model="RE_TAUNTING_01"},
    {name="William Young",model="RE_TAUNTING_MALES_01"},
    {name="Edmund Cooper",model="RE_TORTURINGCAPTIVE_MALES_01"},
    {name="Gilbert Price",model="RE_TOWNCONFRONTATION_MALES_01"},
    {name="Glenn Starr",model="RE_TOWNROBBERY_MALES_01"},
    {name="Max Parker",model="RE_TRAINHOLDUP_MALES_01"},
    {name="Albert Hall",model="RE_TREASUREHUNTER_MALES_01"},
    {name="Guy Phillips",model="RE_WAGONTHREAT_MALES_01"},
    {name="George Butler",model="RE_WASHEDASHORE_MALES_01"},
    {name="Michael Taylor",model="RE_WEALTHYCOUPLE_MALES_01"},
    {name="Donald Hughes",model="S_M_M_Army_01"},
    {name="Hubert Cox",model="S_M_M_ASBCowpoke_01"},
    {name="Julius Edwards",model="S_M_M_ASBDEALER_01"},
    {name="Melvin Alexander",model="S_M_M_BLWCOWPOKE_01"},
    {name="Ted Griffin",model="S_M_M_BLWDEALER_01"},
    {name="Fred Nelson",model="S_M_M_BwmWorker_01"},
    {name="Noah Hickok",model="S_M_M_CghWorker_01"},
    {name="Douglas Powell",model="S_M_M_CKTWorker_01"},
    {name="Floyd Campbell",model="S_M_M_COACHTAXIDRIVER_01"},
    {name="Rufus Hardin",model="S_M_M_CornwallGuard_01"},
    {name="Jack Thompson",model="S_M_M_FussarHenchman_01"},
    {name="Leroy Torres",model="S_M_M_GENCONDUCTOR_01"},
    {name="Paul Patterson",model="S_M_M_HOFGuard_01"},
    {name="Leo Ross",model="S_M_M_LiveryWorker_01"},
    {name="Otto Parker",model="S_M_M_MAGICLANTERN_01"},
    {name="Lewis Miller",model="S_M_M_MaPWorker_01"},
    {name="Emil Jackson",model="S_M_M_MarketVendor_01"},
    {name="Herman Turner",model="S_M_M_MARSHALLSRURAL_01"},
    {name="Willie Flores",model="S_M_M_MicGuard_01"},
    {name="Carl Williams",model="S_M_M_NBXRIVERBOATDEALERS_01"},
    {name="Stephen Rogers",model="S_M_M_ORPGUARD_01"},
    {name="Marvin Scott",model="S_M_M_RACRAILGUARDS_01"},
    {name="Harvey Collins",model="S_M_M_RaCRailWorker_01"},
    {name="Harry Turner",model="S_M_M_RHDCOWPOKE_01"},
    {name="John Perry",model="S_M_M_RHDDEALER_01"},
    {name="Arthur Barnes",model="S_M_M_SDCOWPOKE_01"},
    {name="Chester Hayes",model="S_M_M_SDDEALER_01"},
    {name="Gordon Murphy",model="S_M_M_SDTICKETSELLER_01"},
    {name="Charlie Davis",model="S_M_M_SkpGuard_01"},
    {name="Joe Powell",model="S_M_M_StGSailor_01"},
    {name="Charles Williams",model="S_M_M_STRCOWPOKE_01"},
    {name="Homer Martins",model="S_M_M_STRDEALER_01"},
    {name="Perry Smith",model="S_M_M_StrLumberjack_01"},
    {name="Jay Peters",model="S_M_M_Tailor_01"},
    {name="Dewey Parker",model="S_M_M_TrainStationWorker_01"},
    {name="Warren Barnes",model="S_M_M_UniTrainEngineer_01"},
    {name="Jacob Green",model="S_M_M_ValCowpoke_01"},
    {name="Oscar Dalton",model="S_M_M_VALDEALER_01"},
    {name="Willie Bullion",model="S_M_M_VHTDEALER_01"},
    {name="Bernard Snowden",model="S_M_O_CKTWorker_01"},
    {name="Abraham Turner",model="S_M_Y_Army_01"},
    {name="Will Roberts",model="S_M_Y_RaCRailWorker_01"},
    {name="Carl White",model="U_M_M_ANNOUNCER_01"},
    {name="Isaac Murphy",model="U_M_M_ARMTRAINSTATIONWORKER_01"},
    {name="Lawrence Carter",model="U_M_M_ARMYTRN4_01"},
    {name="Felix Bryant",model="U_M_M_BHT_BANDITOMINE"},
    {name="Mark Ross",model="U_M_M_BHT_BANDITOSHACK"},
    {name="Michael James",model="U_M_M_BHT_BENEDICTALLBRIGHT"},
    {name="Peter Stewart",model="U_M_M_BHT_BLACKWATERHUNT"},
    {name="Bert Long",model="U_M_M_BHT_LOVER"},
    {name="Elijah Jenkins",model="U_M_M_BHT_MINEFOREMAN"},
    {name="Guy Rogers",model="U_M_M_BHT_NATHANKIRK"},
    {name="Elbert O'Driscoll",model="U_M_M_BHT_ODRISCOLLDRUNK"},
    {name="Ray O'Driscoll",model="U_M_M_BHT_ODRISCOLLMAULED"},
    {name="Mack O'Driscoll",model="U_M_M_BHT_ODRISCOLLSLEEPING"},
    {name="Jerry Jones",model="U_M_M_BHT_OLDMAN"},
    {name="Kurt Bayne",model="U_M_M_BHT_OUTLAWMAULED"},
    {name="Matthew Griffin",model="U_M_M_BHT_SAINTDENISSALOON"},
    {name="Tony Moore",model="U_M_M_BHT_SHACKESCAPE"},
    {name="Eddie Cooper",model="U_M_M_BHT_SKINNERBROTHER"},
    {name="Milton Pike",model="U_M_M_BHT_SKINNERSEARCH"},
    {name="Edmund Foster",model="U_M_M_BHT_STRAWBERRYDUEL"},
    {name="Allen Richardson",model="U_M_M_BiVForeman_01"},
    {name="Maurice Howard",model="U_M_M_BlWTrainStationWorker_01"},
    {name="Ralph Scott",model="U_M_M_BULLETCATCHVOLUNTEER_01"},
    {name="Paul Kelly",model="U_M_M_BwmStablehand_01"},
    {name="Calvin Martin",model="U_M_M_CAJHOMESTEAD_01"},
    {name="Kenneth Cox",model="U_M_M_CKTManager_01"},
    {name="Glen Anderson",model="U_M_M_CORNWALLDRIVER_01"},
    {name="Stanley Coleman",model="U_M_M_CrDHomesteadTenant_01"},
    {name="Edgar Starr",model="U_M_M_CRDHOMESTEADTENANT_02"},
    {name="Francis Davis",model="U_M_M_CRDWITNESS_01"},
    {name="Robert Doolin",model="U_M_M_CreoleCaptain_01"},
    {name="Homer Taylor",model="U_M_M_CzPHomesteadFather_01"},
    {name="Nathan Cook",model="U_M_M_DorHomesteadHusband_01"},
    {name="Martin Dunn",model="U_M_M_EmRFarmHand_03"},
    {name="Edwin Bailey",model="U_M_M_EmRFather_01"},
    {name="Bart Rufus",model="U_M_M_EXECUTIONER_01"},
    {name="Patrick Hickok",model="U_M_M_FATDUSTER_01"},
    {name="Jay Lewis",model="U_M_M_FINALE2_AA_UPPERCLASS_01"},
    {name="Thomas Evans",model="U_M_M_GAMDoorman_01"},
    {name="Willis Ward",model="U_M_M_HHRRANCHER_01"},
    {name="Clifton Foreman",model="U_M_M_HtlForeman_01"},
    {name="Roscoe Baker",model="U_M_M_HTLHUSBAND_01"},
    {name="Floyd Williams",model="U_M_M_HtlRancherBounty_01"},
    {name="ISLBUM_01",model="U_M_M_ISLBUM_01"},
    {name="Hubert Patterson",model="U_M_M_LNSOUTLAW_01"},
    {name="Cecil Clark",model="U_M_M_LNSOUTLAW_02"},
    {name="Orville Reed",model="U_M_M_lnsoutlaw_03"},
    {name="Gilbert Johnson",model="U_M_M_LNSOUTLAW_04"},
    {name="Lonnie Hall",model="U_M_M_LnSWorker_01"},
    {name="Wayne Green",model="U_M_M_LnSWorker_02"},
    {name="Clyde Brown",model="U_M_M_LnSWorker_03"},
    {name="Mason Wilson",model="U_M_M_LnSWorker_04"},
    {name="Albert Simmons",model="U_M_M_LrsHomesteadTenant_01"},
    {name="MFRRANCHER_01",model="U_M_M_MFRRANCHER_01"},
    {name="Arnold Price",model="U_M_M_MUD3PIMP_01"}, -- DOES NOT WORK ?? vs CS_strawberryoutlaw_01
    {name="Joe Campbell",model="U_M_M_NbxBankerBounty_01"},
    {name="Everett Sanders",model="U_M_M_NbxBronteAsc_01"},
    {name="Elmer Phillips",model="U_M_M_NbxBronteGoon_01"},
    {name="Perry Hardin",model="U_M_M_NbxBronteSecForm_01"},
    {name="Virgil Henderson",model="U_M_M_NBXGraverobber_01"},
    {name="Eugene Hill",model="U_M_M_NBXGraverobber_02"},
    {name="Irving Butler",model="U_M_M_NBXGraverobber_03"},
    {name="Dan Hayes",model="U_M_M_NBXGraverobber_04"},
    {name="Norman King",model="U_M_M_NBXGraverobber_05"},
    {name="Roosevelt Bennett",model="U_M_M_NBXLiveryWorker_01"},
    {name="Wallace Powell",model="U_M_M_NbxMusician_01"},
    {name="Luther Place",model="U_M_M_NbxResident_01"},
    {name="Gordon Young",model="U_M_M_NbxResident_02"},
    {name="Roger Starr",model="U_M_M_NbxResident_03"},
    {name="Noah Place",model="U_M_M_NbxResident_04"},
    {name="Jack Hart",model="U_M_M_NBXRIVERBOATPITBOSS_01"},
    {name="Douglas Dunn",model="U_M_M_NBXRIVERBOATTARGET_01"},
    {name="Max Bullion",model="U_M_M_NBXShadyDealer_01"},
    {name="Leo Hickok",model="U_M_M_NbxSkiffDriver_01"},
    {name="Russell Ketchum",model="U_M_M_ODDFELLOWPARTICIPANT_01"},
    {name="Julius Cassidy",model="U_M_M_ODriscollBrawler_01"},
    {name="Melvin Hardin",model="U_M_M_ORPGUARD_01"},
    {name="Ted Bart",model="U_M_M_RaCForeman_01"},
    {name="Nelson Doolin",model="U_M_M_RaCQuarterMaster_01"},
    {name="Roland Dalton",model="U_M_M_RhdBackupDeputy_01"},
    {name="Willard Tilghman",model="U_M_M_RhdBackupDeputy_02"},
    {name="Arthur Snowden",model="U_M_M_RhdFiddlePlayer_01"},
    {name="Adam Oakley",model="U_M_M_RhdTrainStationWorker_01"},
    {name="Marvin Foster",model="U_M_M_RhdUndertaker_01"},
    {name="Bennie Robinson",model="U_M_M_RIODONKEYRIDER_01"},
    {name="Harold Cox",model="U_M_M_RKFRANCHER_01"},
    {name="Roy James",model="U_M_M_RKRDONKEYRIDER_01"},
    {name="Nathaniel Adams",model="U_M_M_RWFRANCHER_01"},
    {name="Archie Evans",model="U_M_M_SDBANKGUARD_01"},
    {name="Louis Johnson",model="U_M_M_SDCUSTOMVENDOR_01"},
    {name="David Taylor",model="U_M_M_SDEXOTICSSHOPKEEPER_01"},
    {name="Vernon Alexander",model="U_M_M_SDPHOTOGRAPHER_01"},
    {name="Pete Davis",model="U_M_M_SDSTRONGWOMANASSISTANT_01"},
    {name="Cornelius Martin",model="U_M_M_SDTRAPPER_01"},
    {name="Chester Washington",model="U_M_M_SDWEALTHYTRAVELLER_01"},
    {name="William Morgan",model="U_M_M_SHACKSERIALKILLER_01"},
    {name="Morris Cooper",model="U_M_M_SHACKTWIN_01"},
    {name="Stephen Kelly",model="U_M_M_SHACKTWIN_02"},
    {name="Claude Edwards",model="U_M_M_SKINNYOLDGUY_01"},
    {name="Earl Scott",model="U_M_M_STORY_ARMADILLO_01"},
    {name="Alton Collins",model="U_M_M_story_CANNIBAL_01"},
    {name="Sidney Carter",model="U_M_M_STORY_CHELONIAN_01"},
    {name="Lloyd Walker",model="U_M_M_story_COPPERHEAD_01"},
    {name="August Nelson",model="U_M_M_story_CREEPER_01"},
    {name="Amos Brown",model="U_M_M_STORY_EMERALDRANCH_01"},
    {name="George Roberts",model="U_M_M_story_HUNTER_01"},
    {name="Logan Russell",model="U_M_M_story_MANZANITA_01"},
    {name="Hugh Powell",model="U_M_M_story_MURFEE_01"},
    {name="Bill Patterson",model="U_M_M_story_PIGFARM_01"},
    {name="Dennis Ross",model="U_M_M_story_PRINCESS_01"},
    {name="Red Harlow",model="U_M_M_story_REDHARLOW_01"},
    {name="Wilbur Anderson",model="U_M_M_story_RHODES_01"},
    {name="Clarence Jones",model="U_M_M_STORY_SDSTATUE_01"},
    {name="Daniel Allen",model="U_M_M_story_SPECTRE_01"},
    {name="Leslie Williams",model="U_M_M_story_TREASURE_01"},
    {name="Irvin Ward",model="U_M_M_STORY_TUMBLEWEED_01"},
    {name="Emmett Baker",model="U_M_M_story_VALENTINE_01"},
    {name="Nicholas Miller",model="U_M_M_StrFreightStationOwner_01"},
    {name="Jose Phillips",model="U_M_M_STRWELCOMECENTER_01"},
    {name="Earnest Morris",model="U_M_M_TumGunsmith_01"},
    {name="Clifford White",model="U_M_M_TUMTRAINSTATIONWORKER_01"},
    {name="Jake Jackson",model="U_M_M_UniBountyHunter_01"},
    {name="Charley Moore",model="U_M_M_UniBountyHunter_02"},
    {name="Leroy Wilson",model="U_M_M_UNIDUSTERHENCHMAN_01"},
    {name="Philip Henderson",model="U_M_M_UNIDUSTERHENCHMAN_02"},
    {name="Alfred Bennett",model="U_M_M_UNIDUSTERHENCHMAN_03"},
    {name="Richard Gray",model="U_M_M_UniDusterLeader_01"},
    {name="Jim Price",model="U_M_M_UniExConfedsBounty_01"},
    {name="Otis Stewart",model="U_M_M_UNIONLEADER_01"},
    {name="Leon Hall",model="U_M_M_UNIONLEADER_02"},
    {name="Frederick Richardson",model="U_M_M_UniPeepingTom_01"},
    {name="Ed Mitchell",model="U_M_M_ValAuctionForman_01"},
    {name="Emil Howard",model="U_M_M_ValAuctionForman_02"},
    {name="Glenn Clark",model="U_M_M_ValBarber_01"},
    {name="Liam Barnes",model="U_M_M_ValBearTrap_01"},
    {name="Henry Green",model="U_M_M_ValPokerPlayer_01"},
    {name="Theodore Bell",model="U_M_M_ValPokerPlayer_02"},
    {name="Howard Bailey",model="U_M_M_VALTHEMAN_01"},
    {name="Lester Thomas",model="U_M_M_ValTownfolk_01"},
    {name="Harry Brooks",model="U_M_M_ValTownfolk_02"},
    {name="Herbert Coleman",model="U_M_M_WAPOFFICIAL_01"},
    {name="Lucas Hughes",model="U_M_M_WtCCowboy_04"},
    {name="Sam Watson",model="U_M_O_BHT_DOCWORMWOOD"},
    {name="Tom Turner",model="U_M_O_BLWPHOTOGRAPHER_01"},
    {name="Jerome Bryant",model="U_M_O_CaJHomestead_01"},
    {name="Rudolph Sanders",model="U_M_O_CMRCIVILWARCOMMANDO_01"},
    {name="Percy Wood",model="U_M_O_MaPWiseOldMan_01"},
    {name="Jimmie Perry",model="U_M_O_OLDCAJUN_01"},
    {name="Otto Murphy",model="U_M_O_PSHRancher_01"},
    {name="Frank Thompson",model="U_M_O_RigTrainStationWorker_01"},
    {name="Benjamin Wright",model="U_M_O_VhTExoticShopkeeper_01"},
    {name="Herman Reed",model="U_M_Y_CajHomeStead_01"},
    {name="Ernest Young",model="U_M_Y_CzPHomesteadSon_01"},
    {name="John Harris",model="U_M_Y_CzPHomesteadSon_02"},
    {name="Samuel Rogers",model="U_M_Y_CzPHomesteadSon_03"},
    {name="Franklin Griffin",model="U_M_Y_CZPHOMESTEADSON_04"},
    {name="Victor Hayes",model="U_M_Y_CZPHOMESTEADSON_05"},
    {name="Edward Hill",model="U_M_Y_DuelListBounty_01"},
    {name="Charlie Jenkins",model="U_M_Y_EmRSon_01"},
    {name="Harvey Flores",model="U_M_Y_HtlWorker_01"},
    {name="Phillip Lewis",model="U_M_Y_HtlWorker_02"},
}